DROP TRIGGER IF EXISTS reassessments_guard_delete;
DROP TRIGGER IF EXISTS reassessments_no_update;
DROP TRIGGER IF EXISTS action_events_guard_delete;
DROP TRIGGER IF EXISTS action_events_no_update;
DROP TABLE IF EXISTS reassessments;
DROP TABLE IF EXISTS blockers;
DROP TABLE IF EXISTS action_events;
DROP INDEX IF EXISTS actions_status_idx;
ALTER TABLE actions DROP COLUMN updated_at;
ALTER TABLE actions DROP COLUMN completed_at;
ALTER TABLE actions DROP COLUMN escalation_path;
ALTER TABLE actions DROP COLUMN blocked_reason;
ALTER TABLE actions DROP COLUMN reassessment_trigger;
ALTER TABLE actions DROP COLUMN completion_evidence;
ALTER TABLE actions DROP COLUMN urgency;
ALTER TABLE actions DROP COLUMN effort;
ALTER TABLE actions DROP COLUMN dependencies_json;
ALTER TABLE actions DROP COLUMN required_support_json;
ALTER TABLE actions DROP COLUMN expected_effect;
ALTER TABLE actions DROP COLUMN horizon;
ALTER TABLE actions DROP COLUMN action_key;
